// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqk2Kn7CUm4Jl6phPa5O_Q0yMIZ6DW1ZA',
    appId: '1:893396521609:web:67bcca7db3c282522fac58',
    messagingSenderId: '893396521609',
    projectId: 'fir-cli-sample',
    authDomain: 'fir-cli-sample.firebaseapp.com',
    storageBucket: 'fir-cli-sample.firebasestorage.app',
    measurementId: 'G-2YC163BZCR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp9tj7l4jcYX4C_e8Ae8ZgPABlSY-6jQs',
    appId: '1:893396521609:android:ad11aa552b77b0bd2fac58',
    messagingSenderId: '893396521609',
    projectId: 'fir-cli-sample',
    storageBucket: 'fir-cli-sample.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0B-z88zJVnyV-C-I-59CMVf4dO9dAPoE',
    appId: '1:893396521609:ios:b6fcb651034613b32fac58',
    messagingSenderId: '893396521609',
    projectId: 'fir-cli-sample',
    storageBucket: 'fir-cli-sample.firebasestorage.app',
    androidClientId: '893396521609-qv6bnnd38gtf8q348met9m3mdr0smrkf.apps.googleusercontent.com',
    iosClientId: '893396521609-g6k2rku20a3h14paaqmlsn1n43o4jflo.apps.googleusercontent.com',
    iosBundleId: 'com.example.appNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0B-z88zJVnyV-C-I-59CMVf4dO9dAPoE',
    appId: '1:893396521609:ios:b6fcb651034613b32fac58',
    messagingSenderId: '893396521609',
    projectId: 'fir-cli-sample',
    storageBucket: 'fir-cli-sample.firebasestorage.app',
    androidClientId: '893396521609-qv6bnnd38gtf8q348met9m3mdr0smrkf.apps.googleusercontent.com',
    iosClientId: '893396521609-g6k2rku20a3h14paaqmlsn1n43o4jflo.apps.googleusercontent.com',
    iosBundleId: 'com.example.appNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqk2Kn7CUm4Jl6phPa5O_Q0yMIZ6DW1ZA',
    appId: '1:893396521609:web:3650b845417c814f2fac58',
    messagingSenderId: '893396521609',
    projectId: 'fir-cli-sample',
    authDomain: 'fir-cli-sample.firebaseapp.com',
    storageBucket: 'fir-cli-sample.firebasestorage.app',
    measurementId: 'G-EMTDPEF0EK',
  );

}